import { Transfer } from "antd";

export const endpoints = {
  auth: {
    PATH_LOGIN: "/wms/as/v1/auth/login",
    PATH_REFRESH: "/wms/as/v1/auth/refresh",
    PATH_LOGOUT: "/wms/as/v1/auth/logout",
    PATH_PROFILE:"/wms/as/v1/auth/profile",
  },
  user: {
    PATH_CREATE_USER: "/wms/as/v1/user/create",
    PATH_UPDATE_USER: "/wms/as/v1/user/update",
    PATH_SEARCH_USER: "/wms/as/v1/user/search",
    PATH_DELETE_USER: "/wms/as/v1/user/delete",
    PATH_UPDATE_PASS: "/wms/as/v1/user/update-pass",
    PATH_GET_USER_BY_ROLE: "/wms/as/v1/user/user-by-role",
  },
  materialType: {
    PATH_CREATE_MATERIAL_TYPE: "/wms/whs/v1/ware-house/material-type/create",
    PATH_LIST_MATERIAL_TYPE: "/wms/whs/v1/ware-house/material-type/search",
    PATH_UPDATE_MATERIAL_TYPE: "/wms/whs/v1/ware-house/material-type/update",
    PATH_DETAIL_MATERIAL_TYPE: "/wms/whs/v1/ware-house/material-type/detail",
    PATH_DELETE_MATERIAL_TYPE: "/wms/whs/v1/ware-house/material-type/delete",
  },
  exchangeRate: {
    PATH_CREATE_EXCHANGE_RATE: "/wms/whs/v1/ware-house/material-rate/create",
    PATH_LIST_EXCHANGE_RATE: "/wms/whs/v1/ware-house/material-rate/list",
    PATH_UPDATE_EXCHANGE_RATE: "/wms/whs/v1/ware-house/material-rate/update",
    PATH_DETAIL_EXCHANGE_RATE: "/wms/whs/v1/ware-house/material-rate/detail",
    PATH_DELETE_EXCHANGE_RATE: "/wms/whs/v1/ware-house/material-rate/delete",
  },
  exportWarehouse: {
    PATH_CREATE_TF_WH: "/wms/whs/v1/ware-house/tf/create",
    PATH_SEARCH_TF_WH: "/wms/whs/v1/ware-house/tf/search",
    PATH_UPDATE_TF_WH: "/wms/whs/v1/ware-house/tf/update",
    PATH_DETAIL_TF_WH: "/wms/whs/v1/ware-house/tf/detail",
    PATH_APPROVAL_TF_WH: "/wms/whs/v1/ware-house/tf/approval",
    PATH_SEND_APPROVAL_TF_WH: "/wms/whs/v1/ware-house/tf/send-approval",
  },
  exportRequestWarehouse: {
    PATH_CREATE_TF_WH: "/wms/whs/v1/ware-house/tf/create",
    PATH_SEARCH_TF_WH: "/wms/whs/v1/ware-house/tf/search",
    PATH_UPDATE_TF_WH: "/wms/whs/v1/ware-house/tf/update",
    PATH_DETAIL_TF_WH: "/wms/whs/v1/ware-house/tf/detail",
    PATH_APPROVAL_TF_WH: "/wms/whs/v1/ware-house/tf/approval",
    PATH_SEND_APPROVAL_TF_WH: "/wms/whs/v1/ware-house/tf/send-approval",
  },
  unitType: {
    PATH_CREATE_UNIT_TYPE: "/wms/whs/v1/ware-house/material-unit/create",
    PATH_LIST_UNIT_TYPE: "/wms/whs/v1/ware-house/material-unit/list",
    PATH_UPDATE_UNIT_TYPE: "/wms/whs/v1/ware-house/material-unit/update",
    PATH_DETAIL_UNIT_TYPE: "/wms/whs/v1/ware-house/material-unit/detail",
    PATH_DELETE_UNIT_TYPE: "/wms/whs/v1/ware-house/material-unit/delete",
  },
  provider: {
    PATH_CREATE_PROVIDER: "/wms/whs/v1/ware-house/material-provider/create",
    PATH_LIST_PROVIDER: "/wms/whs/v1/ware-house/material-provider/list",
    PATH_UPDATE_PROVIDER: "/wms/whs/v1/ware-house/material-provider/update",
    PATH_DETAIL_PROVIDER: "/wms/whs/v1/ware-house/material-provider/detail",
    PATH_DELETE_PROVIDER: "/wms/whs/v1/ware-house/material-provider/delete",
  },
  material: {
    PATH_CREATE_MATERIAL: "/wms/whs/v1/ware-house/material-infos/create",
    PATH_LIST_MATERIAL: "/wms/whs/v1/ware-house/material-infos/search",
    PATH_UPDATE_MATERIAL: "/wms/whs/v1/ware-house/material-infos/update",
    PATH_DETAIL_MATERIAL: "/wms/whs/v1/ware-house/material-infos/detail",
    PATH_DELETE_MATERIAL: "/wms/whs/v1/ware-house/material-infos/delete",
    PATH_FETCH_BY_CONDITION_MATERIAL:
      "/wms/whs/v1/ware-house/material-infos/filter",
  },
  importBill: {
    PATH_CREATE_BILL: "/wms/whs/v1/ware-house/im/create",
    PATH_LIST_BILL: "/wms/whs/v1/ware-house/im/search",
    PATH_UPDATE_BILL: "/wms/whs/v1/ware-house/im/update",
    PATH_DETAIL_BILL: "/wms/whs/v1/ware-house/im/detail",
    PATH_DELETE_BILL: "/wms/whs/v1/ware-house/im/delete",
    PATH_ASSIGN_APPROVAL_BILL: "/wms/whs/v1/ware-house/im/send-approval",
    PATH_APPROVE_BILL: "/wms/whs/v1/ware-house/im/approve",
  },
  jobPosition: {
    PATH_LIST_JOB_POSITION: "/wms/as/v1/user/position/search",
    PATH_CREATE_JOB_POSITION: "/wms/as/v1/user/position/create",
    PATH_UPDATE_JOB_POSITION: "/wms/as/v1/user/position/update",
    PATH_DELETE_JOB_POSITION: "/wms/as/v1/user/position/delete",
  },
  jobTitle: {
    PATH_LIST_JOB_TITLE: "/wms/as/v1/user/title/search",
    PATH_CREATE_JOB_TITLE: "/wms/as/v1/user/title/create",
    PATH_UPDATE_JOB_TITLE: "/wms/as/v1/user/title/update",
    PATH_DELETE_JOB_TITLE: "/wms/as/v1/user/title/delete",
  },
  department: {
    PATH_LIST_DEPARTMENT: "/wms/as/v1/org/department/search",
    PATH_CREATE_DEPARTMENT: "/wms/as/v1/org/department/create",
    PATH_UPDATE_DEPARTMENT: "/wms/as/v1/org/department/update",
    PATH_DELETE_DEPARTMENT: "/wms/as/v1/org/department/delete",
  },
  branch: {
    PATH_LIST_BRANCH: "/wms/as/v1/org/branch/search",
    PATH_CREATE_BRANCH: "/wms/as/v1/org/branch/create",
    PATH_UPDATE_BRANCH: "/wms/as/v1/org/branch/update",
    PATH_DELETE_BRANCH: "/wms/as/v1/org/branch/delete",
  },
  warehouse: {
    PREFIX_LIST_WAREHOUSE: "/wms/whs/v1/ware-house/infos/search",
    PREFIX_CREATE_WAREHOUSE: "/wms/whs/v1/ware-house/infos/create",
    PREFIX_DELETE_WAREHOUSE: "/wms/whs/v1/ware-house/infos/delete",
    PREFIX_DETAIL_WAREHOUSE: "/wms/whs/v1/ware-house/infos/detail",
    PREFIX_UPDATE_WAREHOUSE: "/wms/whs/v1/ware-house/infos/update",
    PREFIX_MATERIAL_DETAIL_WAREHOUSE: "/wms/whs/v1/ware-house/infos/materials",
  },
  project: {
    PATH_LIST_PROJECT: "/wms/whs/v1/project/search",
    PATH_CREATE_PROJECT: "/wms/whs/v1/project/create",
    PATH_DELETE_PROJECT: "/wms/whs/v1/project/delete",
    PATH_DETAIL_PROJECT: "/wms/whs/v1/project/detail",
    PATH_UPDATE_PROJECT: "/wms/whs/v1/project/update",
    PATH_ASSIGN_APPROVAL_PROJECT: "/wms/whs/v1/project/send-approval",
    PATH_APPROVE_PROJECT: "/wms/whs/v1/project/approve",
  },
  projectType: {
    PATH_LIST_PROJECT_TYPE: "/wms/whs/v1/project-type/search",
    PATH_CREATE_PROJECT_TYPE: "/wms/whs/v1/project-type/create",
    PATH_DELETE_PROJECT_TYPE: "/wms/whs/v1/project-type/delete",
    PATH_DETAIL_PROJECT_TYPE: "/wms/whs/v1/project-type/detail",
    PATH_UPDATE_PROJECT_TYPE: "/wms/whs/v1/project-type/update",
  },
  projectCategory: {
    PATH_LIST_PROJECT_CATEGORY: "/wms/whs/v1/project-cate/search",
    PATH_CREATE_PROJECT_CATEGORY: "/wms/whs/v1/project-cate/create",
    PATH_DELETE_PROJECT_CATEGORY: "/wms/whs/v1/project-cate/delete",
    PATH_DETAIL_PROJECT_CATEGORY: "/wms/whs/v1/project-cate/detail",
    PATH_UPDATE_PROJECT_CATEGORY: "/wms/whs/v1/project-cate/update",
  },
  object: {
    PATH_LIST_OBJECT: "/wms/whs/v1/objects/partner/search",
    PATH_CREATE_OBJECT: "/wms/whs/v1/objects/partner/create",
    PATH_DELETE_OBJECT: "/wms/whs/v1/objects/partner/delete",
    PATH_DETAIL_OBJECT: "/wms/whs/v1/objects/partner/detail",
    PATH_UPDATE_OBJECT: "/wms/whs/v1/objects/partner/update",
  },
  exportBillWarehouse: {
    PATH_CREATE_BILL: "/wms/whs/v1/ware-house/ex/create",
    PATH_SEARCH_BILL: "/wms/whs/v1/ware-house/ex/search",
    PATH_UPDATE_BILL: "/wms/whs/v1/ware-house/ex/update",
    PATH_DETAIL_BILL: "/wms/whs/v1/ware-house/ex/detail",
    PATH_DELETE_BILL: "/wms/whs/v1/ware-house/ex/delete",
    PATH_APPROVAL_BILL: "/wms/whs/v1/ware-house/ex/approval",
    PATH_ASSIGN_APPROVAL: "/wms/whs/v1/ware-house/ex/send-approval",
  },
  order: {
    PATH_LIST_ORDER: "/wms/whs/v1/order/search",
    PATH_CREATE_ORDER: "/wms/whs/v1/order/create",
    PATH_DELETE_ORDER: "/wms/whs/v1/order/delete",
    PATH_DETAIL_ORDER: "/wms/whs/v1/order/detail",
    PATH_UPDATE_ORDER: "/wms/whs/v1/order/update",
    PATH_UPDATE_STATUS_ORDER: "/wms/whs/v1/order/update-status",
    PATH_ASSIGN_APPROVAL_ORDER: "/wms/whs/v1/order/send-approval",
    PATH_APPROVAL_ORDER: "/wms/whs/v1/order/approval",
  },
  parameterType: {
    PATH_CREATE_PARAMETER_TYPE: "/wms/whs/v1/parameter-type/create",
    PATH_LIST_PARAMETER_TYPE: "/wms/whs/v1/parameter-type/list",
    PATH_UPDATE_PARAMETER_TYPE: "/wms/whs/v1/parameter-type/update",
    PATH_DETAIL_PARAMETER_TYPE: "/wms/whs/v1/parameter-type/detail",
    PATH_DELETE_PARAMETER_TYPE: "/wms/whs/v1/parameter-type/delete",
  },
  parameter: {
    PATH_CREATE_PARAMETER: "/wms/whs/v1/parameter/create",
    PATH_LIST_PARAMETER: "/wms/whs/v1/parameter/list",
    PATH_UPDATE_PARAMETER: "/wms/whs/v1/parameter/update",
    PATH_DETAIL_PARAMETER: "/wms/whs/v1/parameter/detail",
    PATH_DELETE_PARAMETER: "/wms/whs/v1/parameter/delete",
  },
  profession: {
    PATH_CREATE_PROFESSION: "/wms/whs/v1/objects/profession/create",
    PATH_LIST_PROFESSION: "/wms/whs/v1/objects/profession/search",
    PATH_UPDATE_PROFESSION: "/wms/whs/v1/objects/profession/update",
    PATH_DETAIL_PROFESSION: "/wms/whs/v1/objects/profession/detail",
    PATH_DELETE_PROFESSION: "/wms/whs/v1/objects/profession/delete",
  },
};

export const variables = {
  PAGE_VARIABLE: "page",
  LIMIT_VARIABLE: "limit",
};

export const texts = {
  ALL_TEXT: "Tất cả",
  PENDING_TEXT: "Chờ duyệt",
  APPROVED_TEXT: "Đã duyệt",
  REFUSED_TEXT: "Từ chối",
  REQUEST_APPROVAL_TEXT: "Phê duyệt",
  REQUEST_PERSONAL_TEXT: "Đơn của tôi",
};

export const errorTexts = {
  REQUIRE_FIELD: "Trường bắt buộc nhập",
  DATA_EXIST: "Dữ liệu đã tồn tại",
};
export const errorCodes = {
  NAME_EXIST: "NAME_EXIST",
  CODE_EXIST: "CODE_EXIST",
};
export const routes = {
  HOME_PAGE: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  PARTNER: "/partner",
  PROJECT: "/project",
  PROJECT_TYPE: "/project-type",
  PROJECT_TYPE_CREATE: "/project-type/create",
  PROJECT_TYPE_UPDATE: "/project-type/update/",
  PROJECT_CATEGORY: "/project-category",
  PROJECT_CREATE: "/project/create",
  PROJECT_UPDATE: "/project/update/",
  PROJECT_DETAIL: "/project/detail/",
  WAREHOUSE: "/warehouse",
  WAREHOUSE_CREATE: "/warehouse/create",
  WAREHOUSE_EDIT: "/warehouse/edit/",
  WAREHOUSE_DETAIL: "/warehouse-detail/:whCode",
  EX_WAREHOUSE: "/ex-warehouse",
  TRANFER_WAREHOUSE:"/tf-warehouse",
  TRANFER_WAREHOUSE_CREATE:"/tf-warehouse/create",
  TRANFER_WAREHOUSE_DETAIL:"/tf-warehouse/detail/",
  TRANFER_WAREHOUSE_EDIT: "/tf-warehouse/edit/",
  EX_WAREHOUSE_CREATE: "/ex-warehouse/create",
  EX_WAREHOUSE_EDIT: "/ex-warehouse/edit/",
  EX_WAREHOUSE_DETAIL: "/ex-warehouse/detail/",
  IM_WAREHOUSE_CREATE: "/im-warehouse/create",
  IM_WAREHOUSE_UPDATE: "/im-warehouse/update/",
  IM_WAREHOUSE_DETAIL: "/im-warehouse/detail/",
  IM_WAREHOUSE: "/im-warehouse",
  MATERIAL: "/material",
  MATERIAL_CREATE: "/material/create",
  MATERIAL_UPDATE: "/material/update/",
  MATERIAL_TYPE: "/material-type",
  UNIT_TYPE: "/unit-type",
  EXCHANGE_RATE: "/exchange-rate",
  PROVIDER: "/provider",
  REQUEST: "/request",
  TIME_SHEET: "/time-sheet",
  ACCOUNT: "/account",
  JOB_TITLE: "/job-title",
  JOB_POSITION: "/job-position",
  DEPARTMENT: "/department",
  BRANCH: "/branch",
  PERMISSION: "/permission",
  USER_INFO: "/user-info",
  CREATED_DATA: "/create-data",
  PARTNER_CREATE: "/partner/create",
  PARTNER_UPDATE: "/partner/update/",
  ORDER_MANAGEMENT: "/order-management",
  ORDER_CREATE: "/order/create",
  ORDER_UPDATE: "/order/update/",
  ORDER_DETAIL: "/order/detail/",
  ACCOUNT_CREATE: "/create-acount",
  PARAMETER_TYPE: "/parameter-type",
  PARAMETER: "/parameter/",
  PROFESSION: "/profession",
  ATTRIBUTE_MANAGE: "/attribute-management",
  CONTENT_MANAGEMENT: "/content-management",
  DASHBOARD_NEWS_DETAIL: "/dashboard/news/:id",
};
export const storageKey = {
  JWT_TOKEN: "jwtToken",
  REFRESH_TOKEN: "refreshToken",
  USER_INFO: "userInfo",
  USERNAME: "userName",
  USER_ID: "userId",
  USER_CODE: "userCode",
  LIST_GROUP_CODE: "listGroupCode",
  LIST_CATEGORY_CODE: "listCategoryCode",
  LIST_SERVICE_CODE: "listServiceCode",
  LIST_API_CODE: "listApiCode",
  LIST_ENP: "listEnp",
  EXPIRATION: "expiration",
  ID_DEEP_LINK: "idDeepLink",
  DEPARTMENT_LIST: "departmentList",
  POSITION_LIST: "positionList",
  ROLE_TREE: "rolesTree",
  PASSWORD: "password",
};

export const statusUtils = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
};
